name: run
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - python=3.12
  - nextflow>=23.04.4
  - screen

# 1. can be created with:
# conda env create -f environment_run.yml
# 2. or update an existing environment with:
# conda env update -f environment_run.yml