name: dbone
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - python=3.12
  - openjdk=21
  - samtools>=1.21
  - bcftools>=1.21

# 1. can be created with:
# conda env create -f environment_dbone.yml
# 2. or update an existing environment with:
# conda env update -f environment_dbone.yml